### ISSUE TITLE
Unable to disable inline diagnostics

### ISSUE THREAD

**Issue by Yutsuten** [mfussenegger/nvim-lint#124]
I added the following code to my `init.lua` to disable inline diagnostics:

```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false
    }
)
```

Found the code [here](https://github.com/neovim/nvim-lspconfig/issues/662).

This worked for Language Servers (pyls), but it is not being applied for diagnostics generated by nvim-lint. Is it a bug or nvim-lint provides a different way to disable inline diagnostics?

Thank you!

**Comment by Yutsuten** [comment]
Just found the solution to my problem in #123 

```lua
vim.diagnostic.config({virtual_text = false})
```

This works globally.

**Comment by mfussenegger** [comment]
Yes with neovim 0.6 nvim-lint uses the `vim.diagnostic` API, if `vim.diagnostic` isn't available it uses the LSP handler.

My plan is to leave things as they are for a couple more weeks and then drop support for neovim 0.5 - to update the docs to reflect that it uses `vim.diagnostic` and also change the linters to produce the `vim.diagnostic` format instead of the LSP diagnostic format.
