### ISSUE TITLE
Does golangci-lint really accepts file as stdin?

### ISSUE THREAD

**Issue by grundic** [mfussenegger/nvim-lint#167]
The configuration for [golangcilint](https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/golangcilint.lua#L10) sets `stdin = true`, which means that the linter accepts file content through stdin. I haven't found any traces of such functionality in the [official documentation](https://golangci-lint.run/usage/integrations/). I tried running it like

```
$ golangci-lint run --out-format=json --
```

but I just keep getting an error 

```
ERRO [linters context] typechecking error: pattern ./...: directory prefix . outside available modules
```

This is because it starts `golangci-lint` without a filename.
Changing `stdin = true` to `append_fname = true` fixes the problem. But I saw other people were using this linter without such problem, so I'm curious if something is wrong on my side or is this really a bug?

**Comment by mfussenegger** [comment]
I think you're right. @mekpavit you added the linter, do you know more?

**Comment by mekpavit** [comment]
Without an argument 'golangci-lint' will run a linter recursively against the working directory ('./...' by default). Since we don't specify any argument here ('stdin = true'), it will run using './...'.

And as specify in the 'parser' section, this module will loop through each linter result and select only the result of the current file. So, this is why it's working without any filename argument.

But, IMO, your approach is much better. With a filename as a argument, we run the linter against only one file which is much efficient.

**Comment by mfussenegger** [comment]
Looks like there was a reason to omit the filename after all: https://github.com/mfussenegger/nvim-lint/pull/175

**Comment by mekpavit** [comment]
> Looks like there was a reason to omit the filename after all: https://github.com/mfussenegger/nvim-lint/pull/175 

Sorry guys, I should have remember this 🥲

**Comment by grundic** [comment]
Hm.. Mkay.

I would suggest adding a comment to this line for future reference.
