### ISSUE TITLE
Change parameters for a builtin lint

### ISSUE THREAD

**Issue by Mte90** [mfussenegger/nvim-lint#174]
So I was looking to specify a parameter in my case for phpcs.
Looking at the readme I can see how to create a custom one but not how to add a parameter (in the case of phpcs not at first position) or to replace the list of paramaters.

I am looking to migrate from ALE to this plugin

**Comment by mfussenegger** [comment]
You can import the linter and then change the properties. For example if you wanted to customize the args:

```lua
local phpcs = require('lint.linters.phpcs')
phpcs.args = {
  '-q',
  -- new parameter goes here
  '--report=json',
  '-'
}
```

**Comment by Mte90** [comment]
Thanks, maybe add it to the readme?

**Comment by dasupradyumna** [comment]
Hello Mathias!
Sorry for commenting on a closed issue, but I think the problem is relevant to this thread and minor enough to not be a new issue. It took me a while to figure out the correction and get the custom arguments working for my usecase, but the example in the README has a typo.

Current -
```lua
local phpcs = require('lint.linters.phpcs')
```

Expected / Correction -
```lua
local phpcs = require('lint').linters.phpcs
```

**Comment by mfussenegger** [comment]
@dasupradyumna Would you like to create a PR to change it?

**Comment by dasupradyumna** [comment]
Okay, I'll create a PR with the change.
Cheers.
