### ISSUE TITLE
Support for dynamic commands

### ISSUE THREAD

**Issue by YorickPeterse** [mfussenegger/nvim-lint#18]
Some linters may need a dynamic command. For example, RuboCop (https://rubocop.org/) is a popular Ruby linter. Projects managing their Ruby dependencies using Bundler (https://bundler.io/) would have to run RuboCop using `bundle exec rubocop ...`. Projects not using Bundler in turn have to use just `rubocop`.

Looking at the code of nvim-lint, there's only support for a static linter command (i.e. a string). This makes it impossible (I think?) to change the command to run based on the presence of a certain file (or some other condition).

Would it be possible to extend nvim-lint so the `cmd` field can be a function? In that case it would have to return the command to run. Argument wise I think it would only need the buffer number, as that should be enough to derive all the needed information (e.g. the directory of the buffer file).

**Comment by mfussenegger** [comment]
> Would it be possible to extend nvim-lint so the cmd field can be a function? In that case it would have to return the command to run. Argument wise I think it would only need the buffer number, as that should be enough to derive all the needed information (e.g. the directory of the buffer file).

Yes, sounds good to me :+1:

**Comment by mfussenegger** [comment]
https://github.com/mfussenegger/nvim-lint/pull/26 Allows the whole `linter` to be a function, so any option can be set dynamically if necessary.

**Comment by mfussenegger** [comment]
Closing this for now - I think https://github.com/mfussenegger/nvim-lint/pull/26 should be sufficient.

**Comment by ooloth** [comment]
> Closing this for now - I think #26 should be sufficient.

One drawback of only allowing the whole `linter` to be a function (instead of allowing individual options to be functions), is that if we only want to set one option dynamically (e.g. `cmd`), we still have to return the default values for all the other options as well (to avoid wiping them out).

For some linters, that involves copy/pasting quite a bit of custom logic from this repo, making our own configs more complicated than is ideal making it hard to tell which logic represents our change vs. the default values.
