### ISSUE TITLE
How can I create a status line function to show diagnostics in status line?

### ISSUE THREAD

**Issue by praveendhawan** [mfussenegger/nvim-lint#35]

**Comment by mfussenegger** [comment]
You'll have to write a custom function that returns the diagnostics of the current line. See `:help vim.lsp.diagnostic.get()` and `:help statusline`. You can call lua functions in the statusline expressions via `luaeval`.

**Comment by mfussenegger** [comment]
closing this here since it is more neovim diagnostic customization related than nvim-lint specific. If you need further guidance on how to customize it, https://neovim.discourse.group/ may be a better place to ask.

**Comment by rht** [comment]
I'd argue it is relevant to nvim-lint's UX. Coming from Neomake, it out of the box displays the diagnostic text in the status line. This should be the expected default behavior, because diagnostic message is often very long. If this is not out-of-the-box for nvim-lint, at least there should be a quick documentation on how to enable it. I searched for this topic (i.e. `diagnostic status line`) on  https://neovim.discourse.group/, and couldn't find any relevant result. I'm guessing that @praveendhawan didn't go ask there, and might have moved on to other linter plugin.

**Comment by mfussenegger** [comment]
nvim-lint is diagnostics provider/source and not responsible for the display of the diagnostics. The display is responsibility of neovim core or other plugins. 

I won't add any display extensions or documentation in that regard to nvim-lint - at most I can refer to other resources.

**Comment by rht** [comment]
Please make it front and center in the readme that you don't want to be responsible for the display of the diagnostics.
Please make it front and center in the readme that the user has to do their own extra script for a sane auto-linter, instead of having it out of the box.
It's unclear in the readme.

**Comment by mfussenegger** [comment]
See the motivation within the readme:

> nvim-lint instead uses the vim.diagnostic module to present diagnostics in the same way the language client built into neovim does

This already kinda implies that it is not a goal to extend the presentation of the diagnostics. Granted, you need to be able to read between the lines.
Adding presentation extensions would break the separation of concerns. If you disagree with that and think it makes for bad UX I suggest to stick to neomake.

**Comment by praveendhawan** [comment]
Including an example, config or code would people find information faster rather than each one posting their own specific questions in the discourse group.
