### ISSUE TITLE
ALE outputs to Neovim diagnostics by default in 0.6 and above

### ISSUE THREAD

**Issue by w0rp** [mfussenegger/nvim-lint#363]
I thought I'd let you know that ALE outputs to Neovim diagnostics in Neovim 0.6 and above now. I'd also like to make it possible to detect and automatically disable language servers by default if they are configured via lsp-config, so there are no conflicts.

**Comment by bluz71** [comment]
[This merged ALE PR](https://github.com/dense-analysis/ale/pull/4345) introduced a `g:ale_use_neovim_diagnostics_api` option; when set to `1` ALE will send its lint output to Neovim's standard Diagnostic module in the same way `nvim-lint` does.

Hence, the following statement, in the `nvim-lint` README is now outdated and wrong:

> Because ale reports diagnostics with its own home grown solution and even includes its own language server client.

That was true.
However, it is no longer true (since Jan this year).

It would be nice to update the `nvim-lint` README with today's reality; maybe just delete that sentence?

Best regards.

**Comment by mfussenegger** [comment]
Thanks for pointing out. I updated the text
