### ISSUE TITLE
Support fixers?

### ISSUE THREAD

**Issue by entropitor** [mfussenegger/nvim-lint#5]
I really like the idea of this plugin, however, I'm currently also using ALE for fixing / autoformatting as well as linting. Are there any plans on supporting that from this plugin as well / a companion plugin?

**Comment by mfussenegger** [comment]
I don't really have any plans to support fixing or formatting. The scope for this plugin is only linting.

**Comment by ttys3** [comment]
as for fixing and formatting, neovim lsp already support that.

fixing is kind of CodeAction, and formatting is officiallly supported via first level api

**Comment by entropitor** [comment]
@ttys3 "Linting" is also just "Diagnostic" so you could also say it's already supported by LSP. But not all linters / fixers have a LSP implementation, that's why this could be interesting. 

The reason why I am asking is that fixing/formatting is usually part of a linter as a way to automate solving the errors.

**Comment by mfussenegger** [comment]
I can see how it would be appealing to have integrated fixing capabilities, but part of the motivation for this plugin was that the scope that ALE covers is too big (for my requirements).

I don't really want to turn this into another ALE, but rather see it as a more minimal alternative that targets an audience that doesn't need the full feature set of ALE.

If you are happy with the feature set of ALE, why not continue using it. It works and seems to be well maintained.

If somebody wants to re-use some code or build on this to create a fixer/formatter companion plugin that sounds fine for me. I also wouldn't mind to make some API changes in nvim-lint to make it easier to re-use some of the logic.

**Comment by resolritter** [comment]
FWIW I became interested in this plugin precisely because its scope is limited to linting only. I really appreciate it. When plugins do too much, users have to go out of their way to dig the documentation for a way to disable the features they do not want (this is not even always feasible).

I found other plug-ins which already care about formatting: [format.nvim](https://github.com/lukas-reineke/format.nvim), [formatter.nvim](https://github.com/mhartington/formatter.nvim).

I'm still using ALE myself but I'm looking forward to use something else mainly because VimScript is slow. I've had performance issues due to linter giving a lot of warnings, then ALE tries to build hundreds of errors to the quickfix list using VimScript, which is noticeably slow; it becomes a bother to refactor or browse large files because of this. I'm sure there are other performance problems like that one.

**Comment by ttys3** [comment]
> @ttys3 "Linting" is also just "Diagnostic" so you could also say it's already supported by LSP. But not all linters / fixers have a LSP implementation, that's why this could be interesting.
> 
> The reason why I am asking is that fixing/formatting is usually part of a linter as a way to automate solving the errors.

yes, not all lang has a good and working lsp server.

so, I use https://github.com/mhartington/formatter.nvim for those.

**Comment by GasparVardanyan** [comment]
I've started a plugin supporting code actions based on diagnostic messages.
https://github.com/GasparVardanyan/diactions.nvim/tree/master
