### ISSUE TITLE
QUESTION: how are linters found?

### ISSUE THREAD

**Issue by Integralist** [mfussenegger/nvim-lint#617]
👋🏻 

I was curious as to how the linter tools are looked up by this plugin.

For example I have the following configuration that uses the `actionlint` linter:

https://github.com/Integralist/nvim/blob/main/lua/plugins/lint-and-format.lua#L81-L82

```lua
lint.try_lint("actionlint")
```

Now I don't have that linter installed in my normal shell environment...

```shell
$ actionlint -h
zsh: command not found: actionlint
```

But I do have it installed via https://github.com/williamboman/mason.nvim which installs tools into `~/.local/share/nvim/mason/packages/` so does this plugin automatically search for tools in `~/.local/share/nvim` ?

Thanks.

**Comment by Mouarius** [comment]
Hello !
It's because when you install a program with Mason, it adds it automatically to the `PATH` environment variable on Neovim startup !

See : 
[:h mason-introduction](https://github.com/williamboman/mason.nvim/blob/main/doc/mason.txt#L11)
> Packages are installed in Neovim's data directory ([:h standard-path](https://neovim.io/doc/user/starting.html#standard-path)) by default. Executables are linked to a single bin/ directory, which mason.nvim will add to Neovim's PATH during setup, allowing seamless access from Neovim builtins (shell, terminal, etc.) as well as other 3rd party plugins.

If you want to have it accessible in your login shell, you can add the directory of mason binaries to your `PATH` as well !

**Comment by Integralist** [comment]
Ah! Thanks for clarifying 👍
