### ISSUE TITLE
Linting a full project?

### ISSUE THREAD

**Issue by tmcw** [mfussenegger/nvim-lint#633]
Sorry if this is a very newbie question: I've been trying to get something to run my linter (biomejs) over my full project and dump the results in quickfix or diagnostics. It _kind of_ seems like `nvim-lint` could do that, but maybe not - is this part of the goal of the project, or am I looking in the wrong place?

Thanks!

**Comment by dennypenta** [comment]
ahh, I did the same, but too much of code to support, I eventually implement my linter within nvim-lint and was wondering if its worth changing how diagnostics data is collected and handled.
the linters limit the output diagnostics only to the current buffer and it's something I would rather delegate to the diagnostics handlers rather than parsers
